name: Apkggen
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --hidden-import dogpile.cache.backends.memory src/main.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

      - name: Create Release Draft
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Apkggen"
          body: |
            Test.
          draft: true
          prerelease: false

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          update_url: ${{ steps.create_release.outputs.upload_url }}
          if: matrix.platform == 'windows-latest'
          asset_path: dist/apkggen.exe
          if: matrix.platform == 'macos-latest'
          asset_path: dist/apkggen
          if: matrix.platform == 'ubuntu-latest'
          asset_path: dist/apkggen
          asset_name: Apkggen
          assets_content_type: application/zip