name: release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - platform: macos-latest
            target: "--target-arch x86_64"
            id: "macos-x86_64"
          - platform: macos-latest
            target: "--target-arch arm64"
            id: "macos-arm64"
          - platform: "ubuntu-22.04"
            target: ""
            id: "linux"
          - platform: windows-latest
            target: ""
            id: "windows"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        shell: bash
        run: |
          pyinstaller --onefile --noconsole \
            --hidden-import dogpile.cache.backends.memory \
            --name apkggen-${{ matrix.id }} \ 
            src/main.py

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/apkggen-${{ matrix.id }}

