name: build
run-name: build apkggen multi-platform
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --onefile --noconsole --hidden-import dogpile.cache.backends.memory --name apkggen-linux src/main.py

      - name: Build with PyInstaller (macos only)
        if: matrix.os == 'macos-latest'
        run: |
          pyinstaller --onefile --noconsole --hidden-import dogpile.cache.backends.memory --name apkggen-macos src/main.py

      - name: Build with PyInstaller (windows only)
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile --noconsole --hidden-import dogpile.cache.backends.memory --name apkggen-windows src/main.py

      - name: Release for Linux
        uses: softprops/action-gh-release@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          files: dist/apkggen-linux
          tag_name: ${{ github.ref_name }}
          name: "Apkggen"
          draft: true
          prerelease: false

      - name: Release for MACOS
        uses: softprops/action-gh-release@v2
        if: matrix.os == 'macos-latest'
        with:
          files: dist/apkggen-macos
          tag_name: ${{ github.ref_name }}
          name: "Apkggen"
          draft: true
          prerelease: false

      - name: Release for Windows
        uses: softprops/action-gh-release@v2
        if: matrix.os == 'windows-latest'
        with:
          files: dist/apkggen-windows.exe
          tag_name: ${{ github.ref_name }}
          name: "Apkggen ${{ github.ref_name }}"
          draft: true
          prerelease: false
