name: release
run-name: release apkggen multi-platform
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: whichOS
        id: whichos
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "os=linux" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            echo "os=windows" >> "$GITHUB_OUTPUT"
          else
            echo "os=macos" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --hidden-import dogpile.cache.backends.memory --name apkggen-${{ steps.whichOS.outputs.os }} src/main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apkggen-${{ steps.whichos.outputs.os }}
          path: dist/*

  release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
