name: release
run-name: release apkggen multi-platform
on:
  push:
    tags:
      - "v*"

jobs:
  build_linux:
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --noconsole --hidden-import dogpile.cache.backends.memory --name apkggen-${{ matrix.os }} src/main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apkggen-${{ matrix.os }}
          path: dist/*

  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
